# Generated by Django 3.1.13 on 2023-01-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221231_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
