# Generated by Django 4.1.7 on 2023-03-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
