# Generated by Django 3.1.13 on 2023-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
