# Generated by Django 4.1.7 on 2023-03-22 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0002_auto_20230121_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
